Fix many issues
* We now discard invalid builders since I belive it caused these messages [1]
* Fixed determining if users could schedule jobs or not
** This prevented many developers from using the tool at all
* Lots of other improvements to help debug issues in the future

[1]
```
Jan 14 04:41:21 pulse-actions app/worker2.1:   File "/app/pulse_actions/handlers/treeherder_runnable.py", line 70, in on_runnable_job_event
Jan 14 04:41:21 pulse-actions app/worker2.1:     complete=False)
Jan 14 04:41:21 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/sources/buildbot_bridge.py", line 159, in buildbot_graph_builder
Jan 14 04:41:21 pulse-actions app/worker2.1:     if is_downstream(b):
Jan 14 04:41:21 pulse-actions app/worker2.1:   File "/app/.heroku/python/lib/python2.7/site-packages/mozci/platforms.py", line 54, in is_downstream
Jan 14 04:41:21 pulse-actions app/worker2.1:     return get_buildername_metadata(buildername)['downstream']
Jan 14 04:41:21 pulse-actions app/worker2.1: TypeError: 'NoneType' object has no attribute '__getitem__'
```